version: "3.8"

services:
  app:
    build: .
    image: laravel-app
    container_name: laravel-app
    restart: unless-stopped
    ports:
      - "9000:9000"
    volumes:
      - ./:/var/www/html:cached
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: apirestbiblio
      DB_USERNAME: root
      DB_PASSWORD: 
    depends_on:
      - db

  db:
    image: mysql:8
    container_name: laravel-db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: 
      MYSQL_DATABASE: apirestbiblio
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
